---

### 🐳 `docker-compose.yml`

```yaml
services:
  app:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cvdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

